### ISSUE TITLE
Newer Tensorflow Compatibility for neural_net Controller

### ISSUE THREAD

**Issue by zakv** [michaelhush/M-LOOP#37]
Hello,

I'm using M-LOOP with my experiment and so far I've had great results with the gaussian_learner.

I have run into a few issues with the neural_net controller though. It looks like the neuralnet.py uses some deprecated tensorflow features. In particular, when attempting to optimize with it using tensorflow 2.0.0 I get the following error:

```python
Process NeuralNetLearner-1:
Traceback (most recent call last):
  File "C:\Users\user_name\.conda\envs\labscript\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\user_name\.conda\envs\labscript\lib\site-packages\mloop\learners.py", line 1869, in run
    self.create_neural_net()
  File "C:\Users\user_name\.conda\envs\labscript\lib\site-packages\mloop\learners.py", line 1619, in create_neural_net
    n.init()
  File "C:\Users\user_name\.conda\envs\labscript\lib\site-packages\mloop\neuralnet.py", line 493, in init
    self.net = self._make_net(self.last_net_reg)
  File "C:\Users\user_name\.conda\envs\labscript\lib\site-packages\mloop\neuralnet.py", line 431, in _make_net
    return SampledNeuralNet(creator, 1)
  File "C:\Users\user_name\.conda\envs\labscript\lib\site-packages\mloop\neuralnet.py", line 298, in __init__
    self.nets = [self.net_creator() for _ in range(count)]
  File "C:\Users\user_name\.conda\envs\labscript\lib\site-packages\mloop\neuralnet.py", line 298, in <listcomp>
    self.nets = [self.net_creator() for _ in range(count)]
  File "C:\Users\user_name\.conda\envs\labscript\lib\site-packages\mloop\neuralnet.py", line 430, in <lambda>
    self.losses_list)
  File "C:\Users\user_name\.conda\envs\labscript\lib\site-packages\mloop\neuralnet.py", line 60, in __init__
    self.tf_session = tf.Session(graph=self.graph)
AttributeError: module 'tensorflow' has no attribute 'Session'
```

After some Googling, it seems that this is a deprecated way to use tensorflow. One possible work around is to replace `import tensorflow as tf` with the following in neuralnet.py
```python
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
```

That prevented the error and allowed the optimization to proceed, but it produced the following warnings
```python
WARNING:tensorflow:From C:\Users\user_name\.conda\envs\labscript\lib\site-packages\tensorflow_core\python\compat\v2_compat.py:65: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
2020-02-26 18:24:16.228468: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  AVX
To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.
2020-02-26 18:24:16.230358: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 4. Tune using inter_op_parallelism_threads for best performance.
```
So it looks like that work around will likely stop working in a future version of tensorflow. Maybe there is a better way to fix it?

For reference, I have gotten the neural_net controller to work with tensorflow 1.15.0, although it does issue several deprecation warnings.

Cheers,
Zak

**Comment by zakv** [comment]
I've added the workaround mentioned above to my fork of this repo at this commit https://github.com/zakv/M-LOOP/commit/696f3253b7506dbcaeeea3cf35bbbc490372dc13. I also added a version check so that the behavior for tensorflow versions before 2.0.0 remains unchanged.

I'd be happy to submit a pull request for that change if desired

Cheers,
Zak

**Comment by zakv** [comment]
From looking at previous issues it seems like @charmasaur is an expert on the neural net learner; do you have any ideas/suggestions on this topic?

**Comment by charmasaur** [comment]
Hi Zak,

Regarding the 1.15 deprecation warnings, that's expected (unfortunately) -- TensorFlow 1.15 uses a bunch of deprecated APIs from other libraries, and those issue various warnings. On the other hand, they don't actually do any damage, so can just be ignored.

Regarding TensorFlow 2.0 incompatibility, it shouldn't be too hard to do the upgrade properly, it's really just a matter of somebody with the time doing it. Disabling v2 behaviour seems like a reasonable workaround in the meantime. Your approach looks good to me, so I'm happy to merge it if you want to send it as a PR.

Cheers,
Harry

**Comment by zakv** [comment]
Sounds good! I've submitted pull request https://github.com/michaelhush/M-LOOP/pull/41.
